# Generated by Django 4.1.2 on 2023-11-12 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pitapat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertag",
            name="user",
            field=models.ForeignKey(
                db_column="user_key",
                on_delete=django.db.models.deletion.RESTRICT,
                to="pitapat.user",
            ),
        ),
    ]
